#!/bin/sh
# # x-cc -- a C compiler on x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: helium plus cc, with no
#   launcher.  Two absolute paths, both machine facts.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# The launcher-free helium amalgam, x-core: lang.xon declares helium, so the
# suite boots what `x -l cc` boots, less the REPL, and a library beyond it
# arrives only by an import in cc/.  An install has it at boot/, a checkout
# builds it into build/boot/.  lib/x-core.x is not a substitute -- it opens
# with a root-relative include.
for _c in "$X_ROOT/boot/x-core.x" "$X_ROOT/build/boot/x-core.x"; do
	if [ -f "$_c" ]; then X_CORE="$_c"; break; fi
done
if [ -z "${X_CORE:-}" ]; then
	echo "x-cc: no launcher-free helium amalgam under $X_ROOT" >&2
	echo "  looked at boot/x-core.x and build/boot/x-core.x" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

# %install-root first (deferred imports resolve against it), the amalgam (never
# a dialect entry -- those end by starting a REPL), then the bundle root armed
# exactly as run.x arms it. Nothing under cc/ includes a platform module:
# re-including one on a booted tower crashes rather than raising (x-lang#515).
cat > "$OUT" <<EOF
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the two absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_CORE")
(import-path! "$BUNDLE")
(import cc/base)
(set! %repl-print %cc-repl-print)
EOF
